export const ROLE_CODES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  EMPLOYEE: 'EMPLOYEE',
  GUEST: 'GUEST',
  RESEARCH_ADMIN: 'RESEARCH_ADMIN',
  RESEARCHER: 'RESEARCHER',
  COMMITTEE_MEMBER: 'COMMITTEE_MEMBER',
} as const;

export type RoleCode = (typeof ROLE_CODES)[keyof typeof ROLE_CODES];

/** Org/employee modules — EMPLOYEE uses welcome portal only (no module APIs). */
export const READ_ACCESS_ROLES: RoleCode[] = [
  ROLE_CODES.SUPER_ADMIN,
  ROLE_CODES.ADMIN,
  ROLE_CODES.GUEST,
  ROLE_CODES.RESEARCH_ADMIN,
  ROLE_CODES.RESEARCHER,
  ROLE_CODES.COMMITTEE_MEMBER,
];

export const WRITE_ACCESS_ROLES: RoleCode[] = [
  ROLE_CODES.SUPER_ADMIN,
  ROLE_CODES.ADMIN,
  ROLE_CODES.RESEARCH_ADMIN,
];

/** Users selectable for OU approval committees */
export const ADMINISTRATIVE_ROLE_CODES: RoleCode[] = [
  ROLE_CODES.SUPER_ADMIN,
  ROLE_CODES.ADMIN,
  ROLE_CODES.RESEARCH_ADMIN,
  ROLE_CODES.COMMITTEE_MEMBER,
];

export const RPMS_SETTINGS_ROLES: RoleCode[] = [
  ROLE_CODES.SUPER_ADMIN,
  ROLE_CODES.RESEARCH_ADMIN,
];

export const RPMS_RESEARCHER_ROLES: RoleCode[] = [
  ROLE_CODES.SUPER_ADMIN,
  ROLE_CODES.RESEARCH_ADMIN,
  ROLE_CODES.RESEARCHER,
];

/** May assign or change proposal PI (select employee). */
export const RPMS_PI_ASSIGN_ROLES: RoleCode[] = [
  ROLE_CODES.SUPER_ADMIN,
  ROLE_CODES.ADMIN,
  ROLE_CODES.RESEARCH_ADMIN,
];

export const RPMS_COMMITTEE_ROLES: RoleCode[] = [
  ROLE_CODES.SUPER_ADMIN,
  ROLE_CODES.RESEARCH_ADMIN,
  ROLE_CODES.COMMITTEE_MEMBER,
  ROLE_CODES.ADMIN,
];
