export const RESEARCH_PROJECT_STATUS = {
  DRAFT: 'DRAFT',
  REVISION_REQUESTED: 'REVISION_REQUESTED',
  SUBMITTED_TO_COMMITTEE: 'SUBMITTED_TO_COMMITTEE',
  UNDER_COMMITTEE_REVIEW: 'UNDER_COMMITTEE_REVIEW',
  COMMITTEE_APPROVED: 'COMMITTEE_APPROVED',
  COMMITTEE_REJECTED: 'COMMITTEE_REJECTED',
} as const;

export const DEFAULT_CLEARANCE_TYPES = [
  'ANIMAL_ETHICS',
  'HUMAN_ETHICS',
  'BIOSAFETY',
  'ENVIRONMENTAL',
  'INSTITUTIONAL',
] as const;

export const EDITABLE_PROJECT_STATUSES = [
  RESEARCH_PROJECT_STATUS.DRAFT,
  RESEARCH_PROJECT_STATUS.REVISION_REQUESTED,
] as const;

export const DELETABLE_PROJECT_STATUSES = [RESEARCH_PROJECT_STATUS.DRAFT] as const;

export const COMMITTEE_REVIEWABLE_STATUSES = [
  RESEARCH_PROJECT_STATUS.SUBMITTED_TO_COMMITTEE,
  RESEARCH_PROJECT_STATUS.UNDER_COMMITTEE_REVIEW,
] as const;
